version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "8000:8000"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
